# Step 1

In [1]:
import numpy as np

**Declaring a n-D array**

In [2]:
arr = np.array([(2, 4, 8, 11, 12, 19), (12, 14, 13, 11, 31, 78), ("Nafe", "Rafe", "Share", "Fare", "Pakhi", "Barek")])

# General expression: 

# array([ (col1, col2, col3, col4), (col1, col2, col3, col4), (col1, col2, col3, col4) ], additional parameters) 

# [...whole array...]

# (...one row...)

**The data type of an array**

In [3]:
arr.dtype

dtype('<U11')

**The number of axes of an array**

In [4]:
arr.ndim

2

**The shape(dimensions) of an array**

In [5]:
arr.shape

(3, 6)

**The size of an array**

In [6]:
arr.size  # result will be the product of the elements of its shape. In this case, result is 18 = 3 X 6

18

**Size of each element in bytes**

In [7]:
distance = np.array([ (4,5,6), (7,8,9) ])

print(distance.dtype) 

print(distance.itemsize)  # the int32 containe 32 bits as each element. 32/8 = 4 bytes

int32
4


# Step 2

**Reshaping an array**

In [8]:
print('before reshaping: \n', arr)

arr2 = arr.reshape(6,3)  # 'arr' has 3 rows and 6 cols. Here, we're instructing to reshape the array and copy it to 'arr2' which will have 6 rows and 3 cols

print('after reshaping: \n', arr2)

before reshaping: 
 [['2' '4' '8' '11' '12' '19']
 ['12' '14' '13' '11' '31' '78']
 ['Nafe' 'Rafe' 'Share' 'Fare' 'Pakhi' 'Barek']]
after reshaping: 
 [['2' '4' '8']
 ['11' '12' '19']
 ['12' '14' '13']
 ['11' '31' '78']
 ['Nafe' 'Rafe' 'Share']
 ['Fare' 'Pakhi' 'Barek']]


**Creating an array with a/an initial value(/s)**

In [9]:
##### By default, the dtype of the created array is float64 #####

zero_arr = np.zeros((5,4))    # creates a 5X4 array containing 0 as each element 
one_arr = np.ones((4,3))      # creates a 4X3 array containing 1 as each element
rand_arr = np.empty((7,3))    # creates a 7X3 array containing random number as each element

print(zero_arr, end="\n\n")
print(one_arr, end="\n\n")
print(rand_arr, end="\n\n")

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[4.24399158e-314 9.88131292e-324 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]



**np.arange() - when the focus is on the end values**

In [10]:
np.arange(3,10,2)  # starts from 3 and skips 2 in each step till 10    

array([3, 5, 7, 9])

**linspace() - when the focus is on the number of elements between the end values**

In [11]:
np.linspace(0,1,5)  # takes 5 values from 0 to 1; means, cuts the range 0-1 into 5 pieces

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# Basic array operations

**Arithmetic operations on arrays**

*Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result*

In [12]:
# Subtraction

a = np.array([5, 7, 3, 11, 8])
b = np.array([2, 4, 5, 6, 1])

c = a - b 

print(a)
print(b)
print(c)

[ 5  7  3 11  8]
[2 4 5 6 1]
[ 3  3 -2  5  7]


In [20]:
# Elementwise product

a = np.array([2,5,7,6,5])
b = np.array([1,5,7,2,4])

c = a * b 

print(c)  # prints an array

[ 2 25 49 12 20]


In [21]:
# Matrix product

a = np.array([2,5,7,6,5])
b = np.array([1,5,7,2,4])

c = a @ b 

print(c)  # prints a value which will be the sum of the elementwise product of the arrays

108


**Sum of the whole/partial array**

In [39]:
a = np.arange(12).reshape(3,4)

a.sum()          # output: 66
a.sum(axis=0)    # output: [12, 15, 18, 21] 
a.sum(axis=1)    # output: [6, 22, 38] 
a.cumsum(axis=0) # output: [[0, 1, 2, 3],
                 #          [4, 5, 6, 7],
                 #          [8, 9, 10, 11]]

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]])

# Playing more with array

**Performing operation on each element of an array**

In [59]:
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])

for e in arr.flat: 
    print(e**2)

1
4
9
16
25
36
49
64
81
100
121
144


**Getting the flattened array**

In [63]:
flat_arr = arr.ravel()  
print(arr, end="\n\n")  # prints the actual n-D array
print(flat_arr)         # prints a 1-D array containing all the elements of 'arr'

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[ 1  2  3  4  5  6  7  8  9 10 11 12]


**Transpose of a matrix/array**

In [81]:
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

**Modifying the size of the array**

In [85]:
a = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12] 
])

a.resize((6,2))   # unlike reshape(), resize() modifies the array itself

a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])